### ISSUE TITLE
It's bad to use .cn domain.Please think about it.

### ISSUE THREAD

**Issue by gityzon** [yzsong06/yzsong06.github.io#1]
https://blog.bgme.me/posts/precautions-for-registering-domains/

**Comment by yzsong06** [comment]
In the future, it will do COM and CN dual domain names, but the current plan is like this, it is estimated that in a few years

**Comment by yzsong06** [comment]
> https://blog.bgme.me/posts/precautions-for-registering-domains/

In the future, it will do COM and CN dual domain names, but the current plan is like this, it is estimated that in a few years
